### ISSUE TITLE
Following install guide gives "FileNotFoundError: [Errno 2] No such file or directory: 'package/nextgisweb_mapserver/docker.py'"

### ISSUE THREAD

**Issue by Ueland** [nextgis/ngwdocker#1]
Following the install guide causes this exception when running ngwdocker.py:
```python3 ngwdocker.py
Traceback (most recent call last):
  File "ngwdocker.py", line 233, in <module>
    packages = load_packages()
  File "ngwdocker.py", line 55, in load_packages
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'package/nextgisweb_mapserver/docker.py'
```

Looks like there are no docker.py file in nextgisweb_mapserver?

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_mapserver/commit/97b1d431cae71b1a903e5c01bfdfb35538930854
